### ISSUE TITLE
Comparing: ggm_compare_ppc & centrality estimates

### ISSUE THREAD

**Issue by FMTurner** [donaldRwilliams/BGGM#46] opened 2020-07-31 07:30 UTC
Dear BGGM package users/developers,

I would like to ask you two questions about your BGGM package. Any help you could offer on these matters would be greatly appreciated!

**1. Group comparisons:** 
I would not only like to compare two groups/2 networks (i.e., using: BGGM::ggm_compare_ppc). But ideally I would like to see if the difference between 2 groups is larger/smaller than the difference between 2 other groups. Do you know how this could be done?

An example of one of my 4 dataframes looks like this:
```
> head(MENACTIVE)
# A tibble: 6 x 14
  beleifs_2 beleifs_3 beleifs_4 beleifs_5 beleifs_6
      <dbl>     <dbl>     <dbl>     <dbl>     <dbl>
1         5         5         3         2         6
2         2         6         2         2         6
3         2         4         2         4         6
4         2         3         3         5         7
5         1         7         7         1         7
6         1         7         4         1         5
# ... with 9 more variables: beleifs_8 <dbl>,
#   outrage <dbl>, moral <dbl>, motiv_2 <dbl>,
#   motiv_4 <dbl>, motiv_5 <dbl>, id_feminist <dbl>,
#   id_women <dbl>, id_men <dbl>
```

I run the following code to get 6 global network group comparisons

`fitall <-    ggm_compare_ppc(MENACTIVE, WOMENACTIVE, MENINACT, WOMENINACT, test = "global", iter = 1000)`

Resulting in something like this:

![image](https://user-images.githubusercontent.com/69031746/89010785-8ce4da80-d30f-11ea-963d-a637674d4aaf.png)

Now the question is I know active men are different from active women, but I want to know if this difference is larger than the difference between active men and inactive men.

**2. Comparing centrality estimates.**
 I would like to compare if certain nodes are more central in one network than another. I would like then to do something comparable to what is possible using the "NetworkComparisonTest" package with the following code:

`test1<- NCT(MENACTIVE,  WOMENACTIVE, p.adjust.methods = "holm", test.centrality= TRUE,  centrality = c("closeness", "betweenness", "strength"))`

However I am trying to switch to a Bayesian network approach. Perhaps I can do this in BGGM by somehow getting at the posterior samples and using these to calculate the centrality scores for each network & calculate the difference between the centrality scores for each metric? 

Many, many thanks in advance for any help.

**Comment by donaldRwilliams** [comment] 2020-07-31 19:26
Yes, this can all be done but with a bit of work on users end. The reason for this is that I only implemented defaults in the package that I thought about, e.g., I am not so sure what centrality measures other than strength actually mean, not sure of their statistical properties, etc. This is not to say there are inherent issues, but that I have not thought about them enough to implement (which to some degree implies stamp of approval, I think).

Anyhow, here are examples

One possibility for the first thought is to define a custom function to use with `ggm_compare_pcc`. Note in this example, I use sum of squared errors so it could technically be implemented without the custom function (but this is included to see you can compare groups any way you want)

```
library(BGGM)
g1 <- subset(bfi, education == 1)[,1:5]
g2 <- subset(bfi, education == 2)[,1:5]
g3 <- subset(bfi, education == 3)[,1:5]
g4 <- subset(bfi, education == 4)[,1:5]


f <- function(Yg1, Yg2){
  
  # remove NA
  x <- na.omit(Yg1)
  y <- na.omit(Yg2)
  
  # nodes
  p <- ncol(Yg1)
  
  # identity matrix
  I_p <- diag(p)
  
  # partial correlations
  
  pcor_1 <- -(cov2cor(solve(cor(x))) - I_p)
  pcor_2 <- -(cov2cor(solve(cor(y))) - I_p)
  
  # sse
  sum((pcor_1[upper.tri(I_p)] - pcor_2[upper.tri(I_p)])^2)
  
}

# g1 vs g2
obs1 <- f(g1, g2)
fit1 <- ggm_compare_ppc(g1, g2, iter = 1000,  FUN = f, custom_obs = obs1)


# g3 vs g4
obs2 <- f(g3, g4)
fit2 <- ggm_compare_ppc(g3, g4, iter = 1000, FUN = f, custom_obs = obs2)


# diff
obs_diff <- obs1 - obs2

# diff
pred_diff <-  fit1$predictive_custom - fit2$predictive_custom

# any less than, say, 0.05 ?
mean(obs_diff < pred_diff) 
mean(obs_diff > pred_diff)

```

Note you can replace the `sse` with, say, a correlation.  


For the second, you are correct in that you can access the posterior samples and subtract. Here is an example with expected influence using the function `roll_your_own`, which computes anything you want for a partial correlation matrix.


```
fit1 <- estimate(g1)
fit2 <- estimate(g2)
fit3 <- estimate(g3)
fit4 <- estimate(g4)

f <- function(x,...){
  networktools::expectedInf(x,...)$step1
}

e1 <- roll_your_own(object = fit1,
                                FUN = f,
                                select = FALSE,
                                iter = 250)




e2 <- roll_your_own(object = fit2,
                    FUN = f,
                    select = FALSE,
                    iter = 250)


e3 <- roll_your_own(object = fit3,
                    FUN = f,
                    select = FALSE,
                    iter = 250)

e4 <- roll_your_own(object = fit4,
                    FUN = f,
                    select = FALSE,
                    iter = 250)

# first difference
diff1 <- t(e1$results) - t(e2$results)

# second difference
diff2 <- t(e3$results) - t(e4$results)


# difference of difference
diff1 - diff2
```

You could also compute R2 with the function `predictability`, the access the samples, and finally subtract


Here are more examples:

https://donaldrwilliams.github.io/BGGM/articles/ppc_custom.html
https://donaldrwilliams.github.io/BGGM/articles/netstat_custom.html


Hope that helps !

**Comment by donaldRwilliams** [comment] 2020-08-01 04:58
@FMTurner Note also that I labeled this a possible new feature. I have to think if it is something that can be implemented in BGGM. Not sure yet.

**Comment by FMTurner** [comment] 2020-08-04 17:04
So many thanks for this. The code is super useful!!!!

**Comment by donaldRwilliams** [comment] 2020-08-04 17:16
@FMTurner glad it was helpful.

One note is BGGM by design does not implement many defaults. But note that once familiar with how those functions work, it is possible to do everything NCT does, but also so so much more. In those web links, eg, there are a numbers ideas for comparing groups and computing some kind of summary based on the partial correlation matrix (could be the typical,  but also room for more custom hypotheses). 

Also, I could not think of a general way to implement this. So will close the issue for now. But feel free to propose ideas, ask questions, etc

**Closed by donaldRwilliams** 2020-08-04 17:16 UTC
Labels: enhancement, good first issue
