### ISSUE TITLE
Imputation works only for continuous data?

### ISSUE THREAD

**Issue by fdabl** [donaldRwilliams/BGGM#58] opened 2020-12-02 17:55 UTC
Hi Donald,

very cool package!

One thing: reading the documentation of _explore_ and _estimate_, it seems that impute = TRUE implies that you are imputing the missing values during model fitting. But looking at the code, it seems that this is done only when type = continuous; for the other types, it seems that you're doing list-wise deletion, even if impute = TRUE.

I stumbled upon this when looking at the data that is saved in the fitted model and noticing that it had fewer rows than the data I gave BGGM. I was a bit confused, and it is easy to think that one imputes missing data when in fact one is not!

Am I doing something wrong, or should the documentation / implementation be updated?

Cheers,
Fabian

**Comment by donaldRwilliams** [comment] 2020-12-02 18:18
Hi.
That is correct. I started adding in the imputation and had some other things come up. That said, the code is basically written for imputation while model fitting for binary, ordinal, and mixed, but still have to add it in.

For now, because I don't have time to fully implement it. I'll update the package to reflect that only continuous is currently implemented.

**Comment by donaldRwilliams** [comment] 2020-12-02 18:48
Thank you for bringing that to my attention, btw.

I had completely overlooked that, but will fix asap so people don't think their imputing when they are not.

**Comment by donaldRwilliams** [comment] 2020-12-02 22:21
@fdabl I added a message that imputation is only implemented for `type = continuous` when fitting the model.

I figured out how imputation was in the CRAN version. I was contacted sometime ago about making some changes to the packages, due to changes in one of the imported packages. Anyhow, I must have done the work on the branch that I was slowly adding the imputation (no small feat as all the samplers are modified) and merged without considering that. In fact, there actually was a message but it was commented out.

After the checks are done, I will submit the upated version to CRAN.

Also, if you do need imputation done for a particular `type`, please let me know and I can start by adding that one and then you can just install that branch for now.

Best,
Donny

**Comment by donaldRwilliams** [comment] 2020-12-03 03:20
@fdabl I just submitted the updated version to CRAN, so I will close this issue.

Thanks !

**Comment by fdabl** [comment] 2020-12-03 20:31
Awesome, thanks @donaldRwilliams for the quick reply and the quick fix! I'd need the imputation for the mixed type, but I could also do it in mice in case you don't get to it this month. Thanks again!

**Comment by donaldRwilliams** [comment] 2020-12-03 20:56
@fdabl No problem. 

OK. I can do it within the next week or perhaps two at the most. I have been meaning to add it and this provides some motivation :-)

Anyhow, I will comment here when it is added.

**Comment by donaldRwilliams** [comment] 2020-12-05 15:54
@fdabl 

To follow up on this, I took a look at the code (written some time ago), and indeed it is basically ready to be put into BGGM. I will do that over the next couple of days.

**Comment by donaldRwilliams** [comment] 2020-12-08 08:10
@fdabl  

I was taking a look at model recovery and it does not look good enough to put into BGGM at this time. 

Now imputing the datasets is as accurate (as compared to mice), but for some reason the specificity is much too low when imputing while fitting the model.

I also checked fitting the model to the mice imputed datasets using `bggm_missing` and here to specificity (1  - false positive rate) seems to be lower than we would expect, but a bit better than imputing while fitting.

Note these checks were for ordinal data, but I think the issue would arise with mixed data as well. Interestingly, for ordinal data imputation while fitting the model seems to work rather nicely, as does binary data.

I will keep looking into the case of mixed data, as perhaps I have an error somewhere.

**Comment by donaldRwilliams** [comment] 2020-12-08 15:52
@fdabl 

I have it implemented in a branch, but found some slight issues when looking at model recovery (e.g., the false positive rate is higher than expected). I am still looking into and will push it to the master once I figure out the issue, as that should not be the case.

But I checked using mice with `bggm_missing` and this work nicely. The one note is you will also need the development branch from github, as I need to make a small change to it.

```
if (!requireNamespace("remotes")) { 
  install.packages("remotes")   
}   
remotes::install_github("donaldRwilliams/BGGM")
```

**Comment by donaldRwilliams** [comment] 2020-12-08 16:31
I isolated the error, at least I think. 

It seems I made some error when implementing the previously tested samplers into BGGM, as those work fine. So the approach for imputing mixed data seems to work rather nicely, but just need to find out what is different between the versions.

Best,
Donny

**Comment by donaldRwilliams** [comment] 2020-12-08 23:02
@fdabl 

I just pushed to the master. Note I checked it pretty thoroughly. It is also based on Hoff (2007) rank likelihood paper, with a different prior distribution for the precision matrix. I am rather comfortable at this point with it at this point, but of course can use `mice` as well.


```
if (!requireNamespace("remotes")) { 
  install.packages("remotes")   
}   
remotes::install_github("donaldRwilliams/BGGM")

library(BGGM)
pcors <- corpcor::cor2pcor(cor(BGGM::ptsd[,1:10]))
pcors <- ifelse(abs(pcors)  < 0.05, 0, pcors)
cors_true  <- corpcor::pcor2cor(pcors)

set.seed(1)

Y <- BGGM::gen_ordinal(n = 500, p = 10, levels = 5, cor_mat = cors_true)


indices <- which(matrix(0, nrow = nrow(Y), ncol = ncol(Y)) == 0, arr.ind = TRUE)

# 200 NAs
na_indices <- indices[sample(1:nrow(indices), 
                             size = 200, replace = F),]

Y[na_indices] <- NA

# obviously you want more iters
fit_1 <- explore(Y, type = "mixed", 
                iter = 1000, 
                impute = TRUE, 
                mixed_type = rep(1, 10))

sel_1 <- select(fit_1)


# pooled posteriors
# 5 for demonstration
x <- mice::mice(Y, m = 5)

# obviously you want more iters
fit_2 <- bggm_missing(x, iter = 500, 
                      type = "mixed", 
                      method = "explore")

sel_2 <- select(fit_2)


BGGM:::performance(sel_1$Adj_10, 
                   ifelse(pcors == 0, 0, 1))


BGGM:::performance(sel_2$Adj_10, 
                   ifelse(pcors == 0, 0, 1))

```

**Comment by fdabl** [comment] 2020-12-14 11:13
Hey @donaldRwilliams, could it be that this breaks the *predictability* function? It seems that it uses the data with NAs rather than the imputed data, and this leads to the following error:

```
p <- predictability(fit_1, iter = 50)
p

Error in quantile.default(X[[i]], ...) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
```

**Comment by donaldRwilliams** [comment] 2020-12-14 16:20
Yes, probably. 

I am going through all the functions one by one to ensure adding `impute` does not break them before submitting to CRAN. Have not got to predictability yet.

From thinking of it, I think this could entail a rather large change to the `c++` functions for computing predictability. 

Here are two possibilities:

(1) Compute predictability for each of the imputed data sets

(2) Just take the mean of the imputed data sets.

Anyhow, I'll take a look later today to see how long it will take to implement.

**Closed** 2020-12-14 16:31 UTC

**Comment by donaldRwilliams** [comment] 2020-12-14 17:25
@fdabl Here is one idea, in the event it takes too long, that provides a nice inference as to each nodes "importance".

Basically compute KL-divergence, comparing the full multivariate normal dist (or just the joint posterior) to that with each node constrained to zero, which then provides the "distance" or impact on the network by removing a node. Those that have hardly any edges, will barely move the KL. Or switch it and look at an identity matrix vs adding each node.  

The advantage being that then we are not "just" doing regression and it provides a nicely motivated metric, albeit uncommon in practice. Both ways are highly correlated with Bayesian R2 and work directly with the precision matrix (thus all we need is the samples).  If I have time, I hope to write a paper introducing a variety of centrality indices similar to this (although, given it is based on KL, I would just use it in a paper as well :-))

```
library(BGGM)
Y <- BGGM::ptsd

# fit model
fit <- estimate(Y, type = "mixed")

# nodes
p <- ncol(Y)

# full vs node removed
adj <- matrix(1, p, p)
diag(adj) <- 1

# iterations
iter <- fit$iter

cors <- pcor_to_cor(fit)
mat <- matrix(0, nrow = iter, ncol = p)

for(i in 1:p){
  adj[i,1:p] <- 0
  adj[1:p, i] <- 0
  diag(adj) <- 1
  
  for(s in 1:iter){
    
    contrained <- BGGM:::hft_algorithm(Sigma = cors$R[,,s], adj, tol = 1e-10, max_iter = 50)
    
    # or change cors$R_mean to cors$R[,,s] to better account for uncertainty
    mat[s,i] <-   BGGM:::KL_divergnece_mvn(solve(cors$R_mean), contrained$Theta) 

}

  adj <- matrix(1, p, p)

}

pred <- summary(predictability(fit))

cor(as.numeric(colMeans( mat[-1,])), pred $summary$Post.mean)
plot(as.numeric(colMeans( mat[-1,])), pred $summary$Post.mean)

```

**Comment by fdabl** [comment] 2020-12-16 10:28
Hey @donaldRwilliams,

Sounds good, thanks! The KL divergence is an interesting idea, definitely worth exploring. They do a similar thing on DAGs to quantify causal effects, see equation 5 from [here](https://www.nature.com/articles/s41598-019-43033-9) and the Janzing et al. reference.

Something else I want to do is to explore what the model predicts for various fixed node values. But it seems to be implemented only for continuous variables:

```
predict(m)

Error in predict.estimate(m) : 
  type not currently supported. must be continuous
```

I guess you just didn't get around to implement this, right, since Bayesian R2 also uses predicted values? Or am I missing something?

**Comment by donaldRwilliams** [comment] 2020-12-21 17:42
It does indeed use the predicted values, more or less. I am computing Bayesian R2 as the variance in the fitted / variance in the posterior predicted, which was mentioned in one of the first versions of the Bayesian R2 paper. So the `predict` function is actually computing fitted values (in the terminology of base R).

But, yes, I have not gotten around to implementing `posterior_predict` in BGGM. I planned to do this over the winter break.

Also, thanks for all the nice comments :-)

**Comment by donaldRwilliams** [comment] 2020-12-21 19:56
@fdabl  I will also add a function to do what you have in mind, as I think it is quite useful. see here #68. The one challenge will be when imputing missing data during fitting, given I will have to add an option to store all the datasets. Other than that, it will be pretty seamelss.
